web/router.ex
defmodule PhoenixChat.Router do
  use PhoenixChat.Web, :router
  use Coherence.Router  # Added

pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session  # Added
  end

pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true #added whole section
end


  pipeline :api do
    plug :accepts, ["json"]
  end


# Add this block
  scope "/" do
      pipe_through :browser
          coherence_routes
	    end

  # Add this block
    scope "/" do
        pipe_through :protected
	coherence_routes :protected
	      end

  scope "/", PhoenixChat do
      pipe_through :browser
      get "/", PageController, :front
      # add public resources below
	  end
  scope "/", PhoenixChat do
  	pipe_through :browser
	coherence_routes :protected
	get "/chat", PageController, :chat
	end

  scope "/", PhoenixChat do
    pipe_through :protected
    # add protected resources below
	resources "/users", UserController
    	put "/lock/:id", UserController, :lock
    	put "/unlock/:id", UserController, :unlock
    	put "/confirm/:id", UserController, :confirm
	resources "/privates", PhoenixChat.PrivateController
  end
end

lib/phoenix_chat/endpoint.ex
defmodule PhoenixChat.Endpoint do
  use Phoenix.Endpoint, otp_app: :phoenix_chat

  socket "/socket", PhoenixChat.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :phoenix_chat, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_phoenix_chat_key",
    signing_salt: "G2cHn98U"

  # Add Timber plugs for capturing HTTP context and events
  plug Timber.Integrations.ContextPlug
  plug Timber.Integrations.EventPlug

  plug PhoenixChat.Router
end

lib/phoenix_chat/repo.ex
defmodule PhoenixChat.Repo do
  use Ecto.Repo, otp_app: :phoenix_chat
end

web/models/coherence/user.ex
defmodule PhoenixChat.User do
  use PhoenixChat.Web, :model
  use Coherence.Schema

  schema "users" do
    field :name, :string
    field :email, :string
    coherence_schema

    timestamps
  end

  def changeset(model, params \\ %{}) do
    model
    |> cast(params, [:name, :email] ++ coherence_fields)
    |> validate_required([:name, :email])
    |> validate_format(:email, ~r/@/)
    |> unique_constraint(:email)
    |> validate_coherence(params)
  end
end

web/controllers/page_controller.ex
defmodule PhoenixChat.PageController do
  use PhoenixChat.Web, :controller

  def chat(conn, _params) do
    render conn, "chat.html"
  end
  def front(conn, _params) do
      render(conn, "front.html")
      end
end

web/controllers/user_controller.ex
defmodule PhoenixChat.UserController do
  use PhoenixChat.Web, :controller

  alias PhoenixChat.User

  def index(conn, _params) do
    users = Repo.all(User)
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = User.changeset(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    changeset = User.changeset(%User{}, user_params)

    case Repo.insert(changeset) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: user_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Repo.get!(User, id)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Repo.get!(User, id)
    changeset = User.changeset(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Repo.get!(User, id)
    changeset = User.changeset(user, user_params)

    case Repo.update(changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Repo.get!(User, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: user_path(conn, :index))
  end
end

web/views/coherence/coherence_view.ex
defmodule Coherence.CoherenceView do
  use PhoenixChat.Coherence.Web, :view
end

web/views/coherence/email_view.ex
defmodule Coherence.EmailView do
  use PhoenixChat.Coherence.Web, :view

end

web/views/coherence/layout_view.ex
defmodule Coherence.LayoutView do
  use PhoenixChat.Coherence.Web, :view


end

web/views/coherence/password_view.ex
defmodule Coherence.PasswordView do
  use PhoenixChat.Coherence.Web, :view

end

web/views/coherence/registration_view.ex
defmodule Coherence.RegistrationView do
  use PhoenixChat.Coherence.Web, :view

end

web/views/coherence/session_view.ex
defmodule Coherence.SessionView do
  use PhoenixChat.Coherence.Web, :view


end

web/views/coherence/unlock_view.ex
defmodule Coherence.UnlockView do
  use PhoenixChat.Coherence.Web, :view


end

web/views/error_view.ex
defmodule PhoenixChat.ErrorView do
  use PhoenixChat.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule PhoenixChat.LayoutView do
  use PhoenixChat.Web, :view
end

web/views/page_view.ex
defmodule PhoenixChat.PageView do
  use PhoenixChat.Web, :view
end

web/views/user_view.ex
defmodule PhoenixChat.UserView do
  use PhoenixChat.Web, :view
end

web/templates/coherence/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>LightChat</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
        </nav>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://use.fontawesome.com/d9108e2343.js"></script>
  </body>
</html>

web/templates/coherence/layout/email.html.eex
<html>
  <head>
    <title><%= @email.subject %></title>
  </head>
  <body>
    <%= render @view_module, @view_template, assigns %>
  </body>
</html>

web/templates/coherence/password/edit.html.eex
<br \>

<h3>Create a New Password</h3>

<%= form_for @changeset, password_path(@conn, :update, @changeset.data), [as: :password], fn f  -> %>

  <%= hidden_input f, :reset_password_token %>

  <div class="form-group">
    <%= required_label f, :password, class: "control-label" %>
    <%= password_input f, :password, class: "form-control", required: "" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= required_label f, :password_confirmation, class: "control-label" %>
    <%= password_input f, :password_confirmation, class: "form-control", required: "" %>
    <%= error_tag f, :password_confirmation %>
  </div>

  <div class="form-group">
    <%= submit "Update Password", class: "btn btn-primary" %>
    <%= link "Cancel", to: Coherence.Config.logged_out_url("/"), class: "btn" %>
  </div>
<% end %>

web/templates/coherence/password/new.html.eex
<br \>

<h3>Send reset password link</h3>

<%= form_for @changeset, password_path(@conn, :create), [as: :password], fn f  -> %>

  <div class="form-group">
    <%= required_label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control", required: "" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= submit "Reset Password", class: "btn btn-primary" %>
    <%= link "Cancel", to: Coherence.Config.logged_out_url("/"), class: "btn" %>
  </div>
<% end %>

web/templates/coherence/session/new.html.eex
<div class="jumbotron">
  <h2><%= gettext "LightChat"%></h2><i class="fa fa-comments fa-3x" aria-hidden="true"></i>
  <p class="lead">A new simple chat app</p>
</div>


<br \>

<%= form_for @conn, session_path(@conn, :create), [as: :session], fn f  -> %>

  <% login_field = Coherence.Config.login_field %>
  <div class="form-group">
    <%= required_label f, login_field, class: "control-label" %>
    <%= text_input f, login_field, class: "form-control", required: "" %>
    <%= error_tag f, login_field %>
  </div>

  <div class="form-group">
    <%= required_label f, :password, class: "control-label" %>
    <%= password_input f, :password, class: "form-control", required: "" %>
    <%= error_tag f, :password %>
  </div>

  <%= if @remember do %>
    <div class="form-group">
      <input type="checkbox"  name="remember"> Remember Me?
    </div>
    <br />
  <% end %>

  <div class="form-group">
    <%= submit "Sign In", class: "btn btn-primary" %>
    <%= link "Cancel", to: Coherence.Config.logged_out_url("/"), class: "btn" %>
  </div>

  <div class="form-group">
    <%= coherence_links(@conn, :new_session) %>
  </div>

<% end %>

web/templates/coherence/unlock/new.html.eex
<br \>

<%= form_for @conn, unlock_path(@conn, :create), [as: :unlock], fn f  -> %>

  <div class="form-group">
    <%= required_label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control", required: "" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= required_label f, :password, class: "control-label" %>
    <%= password_input f, :password, class: "form-control", required: "" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= submit "Send Instructions", class: "btn btn-primary" %>
    <%= link "Cancel", to: Coherence.Config.logged_out_url("/"), class: "btn" %>
  </div>

<% end %>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello PhoenixChat!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <%= if Coherence.current_user(@conn) do %>
	<%= if @conn.assigns[:remembered] do %>
	<li style="color: red;">!!</li>
	<% end %>
	<% end %>
	<div>maybe a navbar or something?</div>
	</header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://use.fontawesome.com/d9108e2343.js"></script>
    
  </body>
</html>

web/templates/page/chat.html.eex
<div class="jumbotron">
  <h2><%= gettext "LightChat"%></h2><i class="fa fa-comments fa-3x" aria-hidden="true"></i>
  <p class="lead">A new simple chat app</p>
</div>

<div class="row">
  <div class="col-md-4 alert alert-info">
    Hello, <span id="User"><%= @current_user.name %></span>.
  </div>
  <div class="col-md-9">
    <h2>Messages</h2>
    <ul id="MessageList" class="list-unstyled" style="height: 500px; border: 1px solid #ccc; overflow-y: auto; padding: 20px"></ul>
    <div>Your message:<p></div>
    <input type="text" id="NewMessage" placeholder="Type and press enter..." class="form-control"><br>
    <div><%= link "Log out", to: session_path(@conn, :delete), method: "delete" %></div>
  </div>
  
  <div class="col-md-3">
    <h2>Online</h2>
    <ul id="UserList" class="list-unstyled">
      <li>Loading online users...</li>
    </ul>
  </div>
</div>

web/templates/page/front.html.eex
<div class="jumbotron">
  <h2><%= gettext "LightChat"%></h2><i class="fa fa-comments fa-3x" aria-hidden="true"></i>
  <p class="lead">A new simple chat app</p>
</div>
<div>New here? Would you like to <a href="http://sundown.51percent.tech:8080/registrations/new">register to chat?</a><p></div>
<div>Or, go ahead and <a href="http://sundown.51percent.tech:8080/sessions/new">Login</a></div>

web/templates/user/edit.html.eex
<h2>Edit user</h2>

<%= render "form.html", changeset: @changeset,
                        action: user_path(@conn, :update, @user) %>

<%= link "Back", to: user_path(@conn, :index) %>

web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :bio, class: "control-label" %>
    <%= text_input f, :bio, class: "form-control" %>
    <%= error_tag f, :bio %>
  </div>

  <div class="form-group">
    <%= label f, :number_of_pets, class: "control-label" %>
    <%= number_input f, :number_of_pets, class: "form-control" %>
    <%= error_tag f, :number_of_pets %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/user/index.html.eex
<h2>Listing users</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Bio</th>
      <th>Number of pets</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.bio %></td>
      <td><%= user.number_of_pets %></td>

      <td class="text-right">
        <%= link "Show", to: user_path(@conn, :show, user), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New user", to: user_path(@conn, :new) %>

web/templates/user/new.html.eex
<h2>New user</h2>

<%= render "form.html", changeset: @changeset,
                        action: user_path(@conn, :create) %>

<%= link "Back", to: user_path(@conn, :index) %>

web/templates/user/show.html.eex
<h2>Show user</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @user.name %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>

  <li>
    <strong>Bio:</strong>
    <%= @user.bio %>
  </li>

  <li>
    <strong>Number of pets:</strong>
    <%= @user.number_of_pets %>
  </li>

</ul>

<%= link "Edit", to: user_path(@conn, :edit, @user) %>
<%= link "Back", to: user_path(@conn, :index) %>